### ISSUE TITLE
请问一下作者能否提供Ohsumed的原始数据？

### ISSUE THREAD

**Issue by VVVINCENTJ** [DQ0408/KERM#1]
通过这个链接（ http://disi.unitn.it/moschitti/corpora.htm ）可以下载Ohsumed的文档集合，但似乎无法在页面上找到query文件以及相关性文件。 
请问一下query文件以及相关性文件是存放在这个FTP地址（ ftp://medir.ohsu.edu/pub/ohsumed ）里的吗？但是目前我无法访问这个FTP地址。
最后希望作者能够提供一下的Ohsumed的原始数据，十分感谢你的帮助！

**Comment by DQ0408** [comment]
Hi, Ohsumed是做文本分类的，所以没有提供query和qrel，这是我们根据文本分类的label构建的Ohsumed的[query和qrel](https://github.com/DQ0408/KERM/tree/main/data/ohsumed)，希望有帮助~

**Comment by VVVINCENTJ** [comment]
谢谢作者的及时回复。这边还有个小问题，我注意到qrels文件中的文档ID似乎和我下载的文档集合中的文档ID不匹配。如果作者你不介意的话，希望能再提供一下所用到的文档集合。
感谢！

**Comment by DQ0408** [comment]
hi, 下载链接更新到[readme](https://github.com/DQ0408/KERM/tree/main/data/ohsumed)了
